"""Prompts for the task decomposition workflow."""

PROMPTS = {
    "system_prompt": (
        "You are an expert software architect and technical lead specializing in breaking down complex "
        "features into small, manageable tasks. You excel at creating detailed, actionable subtasks "
        "with clear acceptance criteria. You understand software development best practices and "
        "focus on creating tasks that follow the Single Responsibility Principle."
    ),
    "generate_issues": (
        "Your task is to create a list of user stories for a requested feature.\n"
        "Feature: {issue_spec}\n"
        "A repository has already been checked out for you. Examine the existing code and then think through, "
        "step by step, which user stories are needed to implement the feature.\n"
        "Generate user stories in the order they need to be implemented.\n"
        "IMPORTANT: It is VITAL that you avoid over-engineering. The feature should be fully implemented but "
        "you must avoid unnecessary complexity.\n"
        "For each user story, you must provide:\n"
        "1. A clear, specific title\n"
        "2. A description that contains a user story in the format of "
        "'As a [role], I want [feature] so that [benefit].'\n"
        "3. Any additional information that is needed to understand the context of the user story.\n"
        "Keep in mind that user stories are written from the perspective of the end user of the product, "
        "NOT the development team.\n"
    ),
    "validate_issues": (
        "A project manager has created a list of user stories for a requested feature. Please review them and "
        "determine if they should be accepted or rejected.\n"
        "This is the feature to be implemented:\n"
        "{issue_spec}\n"
        "The feature has been broken down into the following user stories:\n"
        "{issues}\n"
        "Consider the user stories as a whole and determine if they comprehensively cover the feature.\n"
        "Carefully consider each user story and determine if it:\n"
        "1. Makes sense and is an essential part of the feature\n"
        "2. Is not over-engineered\n"
        "3. Does not overlap with other user stories\n"
        "4. Is arranged in the correct order\n"
        "If any problems are found, provide an updated list of user stories that are valid.\n"
        "If there none of the problems above are found, use the 'approve_issues' tool to approve the user stories. "
        "Do not generate new user stories if the only improvements are minor wording changes.\n"
    ),
    "decompose_feature": (
        "You are creating user stories and subtasks as part of a plan to implement the following feature: "
        "{issue_spec}\n"
        "The feature has been broken down into the following user stories:\n"
        "{issues}\n"
        "The specific user story you are planning to implement is: {feature_spec}\n"
        "A repository has already been checked out for you. Examine the existing code and then think through, "
        "step by step, which tasks are needed to implement the user story.\n"
        "For each task, you must provide:\n"
        "1. A clear, specific title\n"
        "2. A detailed description of the work required\n"
        "3. Quantifiable acceptance criteria that can be verified through automated tests\n\n"
        "Guidelines for task breakdown:\n"
        "- Each task should follow the Single Responsibility Principle - do one thing and do it well\n"
        "- Tasks should represent a single logical change (e.g., one schema change, one API endpoint)\n"
        "- Tasks should be independently testable with specific test cases\n"
        "- Each acceptance criterion must be measurable through unit tests, integration tests, or E2E tests\n"
        "- Tasks should be small enough that their implementation approach is clear\n"
        "- Consider separation of concerns (e.g., separate backend/frontend/database tasks)\n"
        "- Include necessary setup/infrastructure tasks\n"
        "- Tasks should be specific and focused\n"
        "- Tasks should include detailed steps\n"
        "- Every task must be a clear, actionable software development task that results in a code change\n"
        "- Consider using try logic to handle potential exceptions appropriately\n\n"
        "IMPORTANT: It is VITAL that you avoid over-engineering. The feature should be fully implemented but "
        "you must avoid unnecessary complexity. Do not include tasks that are not directly related to the feature. "
        "Do not include functionality beyond the user story.\n"
        "IMPORTANT: Make sure each task is discrete and doesn't overlap with other tasks.\n"
    ),
    "validate_subtasks": (
        "Review the following subtasks to ensure they meet these criteria:\n"
        "1. Each task follows the Single Responsibility Principle\n"
        "2. Each task represents a single logical change\n"
        "3. Each acceptance criterion is quantifiably measurable through automated tests\n"
        "4. Test coverage requirements are explicitly specified\n"
        "5. Performance criteria are measurable where applicable\n"
        "6. No critical aspects of the feature are missing\n"
        "7. Each task requires a code change\n\n"
        "Subtasks to validate:\n{subtasks}\n\n"
        "If any issues are found, provide specific recommendations for improvement."
    ),
    "regenerate_subtasks": (
        "You are creating user stories and subtasks as part of a plan to implement the following feature: "
        "{issue_spec}\n"
        "A user story has been broken down into subtasks but some were deemed invalid.\n"
        "Your task is to regenerate the subtasks based on the feedback provided.\n"
        "The feature has been broken down into the following user stories:\n"
        "{issues}\n"
        "The specific user story that was broken down into subtasks is: {feature_spec}\n"
        "Original Subtasks: {subtasks}\n"
        "Failed Subtasks: {auditedSubtasks}\n"
        "Feedback: {feedbacks}\n"
        "A repository has already been checked out for you. Examine the existing code and then think through, "
        "step by step, which tasks are needed to implement the user story.\n"
        "For each task, you must provide:\n"
        "1. A clear, specific title\n"
        "2. A detailed description of the work required\n"
        "3. Quantifiable acceptance criteria that can be verified through automated tests\n\n"
        "Guidelines for task breakdown:\n"
        "- Each task should follow the Single Responsibility Principle - do one thing and do it well\n"
        "- Tasks should represent a single logical change (e.g., one schema change, one API endpoint)\n"
        "- Tasks should be independently testable with specific test cases\n"
        "- Each acceptance criterion must be measurable through unit tests, integration tests, or E2E tests\n"
        "- Tasks should be small enough that their implementation approach is clear\n"
        "- Consider separation of concerns (e.g., separate backend/frontend/database tasks)\n"
        "- Include necessary setup/infrastructure tasks\n"
        "- Tasks should be specific and focused\n"
        "- Tasks should include detailed steps\n"
        "- Every task must be a clear, actionable software development task that results in a code change\n"
        "- Consider using try logic to handle potential exceptions appropriately\n\n"
    ),
    "dependency_tasks": (
        "Review the following target task and determine if it depends on any other tasks.\n"
        "Target task: {target_task}\n"
        "Other tasks:\n{subtasks}\n\n"
        "Dependencies should always be one way, marking which tasks a task depends on.\n"
        "If any dependencies are found, link the uuid of the target task "
        "with a list of uuids for any tasks it depends on.\n"
        "IMPORTANT: do not create circular dependencies.\n"
    ),
    "generate_system_prompts": (
        "Your task is to create a comprehensive system prompt that will guide an AI agent in implementing "
        "the entire feature and all its tasks:\n\n"
        "Issue spec: {issue_spec}\n"
        "Issues: {issues}\n"
        "Tasks: {tasks}\n\n"
        "Create a single system prompt that:\n"
        "1. Defines the AI's role and expertise needed for implementing the entire feature\n"
        "2. Provides comprehensive context about the feature, its issues, and all tasks\n"
        "3. Sets clear guidelines and constraints that apply across all tasks\n"
        "4. Specifies coding standards and best practices to follow throughout implementation\n"
        "5. Includes technical requirements and architectural considerations\n"
        "6. Explains how different tasks relate to and depend on each other\n"
        "7. Provides guidance on maintaining consistency across all implementations\n\n"
        "Format the system prompt as follows:\n"
        "---\n"
        "Feature Overview:\n"
        "[High-level description of the feature and its goals]\n\n"
        "AI Role and Expertise:\n"
        "[Define the AI's role and required expertise]\n\n"
        "Implementation Context:\n"
        "[Comprehensive context about the feature and its components]\n\n"
        "Technical Guidelines:\n"
        "- [List technical requirements and architectural guidelines]\n\n"
        "Coding Standards:\n"
        "- [List coding standards and best practices]\n\n"
        "Task Dependencies and Relationships:\n"
        "[Explain how tasks relate to and depend on each other]\n\n"
        "Quality and Testing Requirements:\n"
        "[Specify quality standards and testing requirements]\n"
        "---\n"
    ),




    ###################################DOCS PROMPTS##########################################
    "docs_system_prompt": (
        "You are an expert technical writer and documentation specialist. You excel at creating clear, comprehensive, and user-friendly "
        "documentation that follows industry standards and helps users effectively use the software."
    ),
    "docs_generate_issues": (
        "Your task is to create a list of documentation tasks for the repository.\n"
        "A repository has already been checked out for you. Examine the existing code and then think through, "
        "Documentation tasks must be created based on the following rules:\n"
        "1. Create a issue for overall documentation for the repository\n"
        "2. For each significant folder in the codebase, create a documentation task for it.\n"
        "3. For any file that is complex (over 200 lines), create a separate documentation task for that file.\n"
        "4. For each documentation task, you must provide:\n"
        "   - A clear, specific title in the following format. [Type: Path/File];[Folder/File Path];[Readme File Name];\n"
        "   - A description that includes any additional information.\n"
        "Keep in mind that documentation should be written from the perspective of the end user, "
        "focusing on their needs and use cases.\n"
    ),
    "docs_validate_issues": (
        "A technical writer has created a list of documentation tasks for the repository. Please review them and "
        "determine if they should be accepted or rejected.\n"
        "The documentation has been broken down into the following tasks:\n"
        "{issues}\n"
        "Consider the documentation tasks as a whole and determine if they comprehensively cover the repository.\n"
        "Carefully consider each task and determine if it satisfies the following criteria:\n"
        "Documentation tasks must be created based on the following rules:\n"
        "1. Create a issue for overall documentation for the repository\n"
        "2. For each significant folder in the codebase, create a documentation task for it.\n"
        "3. For any file that is complex (over 200 lines), create a separate documentation task for that file.\n"
        "4. For each documentation task, you must provide:\n"
        "   - A clear, specific title in the following format: [Type: Path/File];[Folder/File Path];[Readme File Name];\n"
        "   - A description that includes any additional information needed to understand what needs to be documented.\n"
        "5. The documentation should be written from the perspective of the end user.\n"
        "6. Each task should be distinct and not overlap with other tasks.\n"
        "Please only reject if there are significant issues that would significantly impact the quality or usability of the documentation.\n"
    ),
    "docs_decompose_feature": (
        "You are creating documentation readme file's sections/headings as part of a plan to document the following folder and readme file:\n"
        "{issues}\n"
        "A repository has already been checked out for you. Examine the existing code and then think through, "
        "step by step, which task sections are needed to fully document this section.\n"
        "For each task section, you must provide:\n"
        "1. A clear, specific title that describes the section's purpose\n"
        "2. A description in the following format: [Type: Path/File];[Folder/File Path];[Readme File Name];\n"
        "3. Documentation requirements that must include:\n"
        "   - Purpose and scope of the section\n"
        "   - Key concepts or features to be documented\n"
        "   - Required code examples or snippets (if applicable)\n"
        "   - Any diagrams or visual aids needed\n"
        "   - Links to related documentation sections\n\n"
        "Guidelines for task section breakdown:\n"
        "- Each readme section should represent a major functional component or feature\n"
        "- Sections should be logically organized and flow naturally\n"
        "- Consider dependencies between sections\n"
        "- Each section should be self-contained but reference related sections\n\n"
        "IMPORTANT: Make sure each section is distinct and doesn't overlap with other sections.\n"
    ),
    "docs_validate_subtasks": (
        "Review the following documentation sections to ensure they meet these criteria:\n"
        "1. Title Requirements:\n"
        "   - Title is clear and specific\n"
        "   - Title accurately describes the section's purpose\n\n"
        "2. Description Format:\n"
        "   - Must follow the format: [Type: Path/File];[Folder/File Path];[Readme File Name];\n"
        "   - All three components must be present and valid\n\n"
        "3. Documentation Requirements:\n"
        "   - Purpose and scope are clearly defined\n"
        "   - Key concepts or features are identified\n"
        "   - Required code examples are specified (if applicable)\n"
        "   - Any needed diagrams or visual aids are listed\n"
        "   - Links to related sections are included\n\n"
        "4. Section Organization:\n"
        "   - Section is logically placed in the documentation\n"
        "   - No significant overlap with other sections\n"
        "   - Dependencies on other sections are properly identified\n\n"
        "Sections to validate:\n{subtasks}\n\n"
        "A section should be approved if it generally meets these criteria. Only reject if there are significant issues that would impact the quality or usability of the documentation.\n"
    ),
    "docs_regenerate_subtasks": (
        "A documentation task has been broken down into sections but some were deemed invalid.\n"
        "Your task is to regenerate the sections based on the feedback provided.\n"
        "The documentation has been broken down into the following main sections:\n"
        "{issues}\n"
        "Original sections: {subtasks}\n"
        "Failed sections: {auditedSubtasks}\n"
        "Feedback: {feedbacks}\n"
        "A repository has already been checked out for you. Examine the existing code and then think through, "
        "step by step, which task sections are needed to fully document this section.\n"
        "For each task section, you must provide:\n"
        "1. title of the section\n"
        "2. a description in the following format. [Type: Path/File];[Folder/File Path];[Readme File Name];\n"
        "3. Specific documentation requirements and quality criteria\n\n"
        "Guidelines for task section breakdown:\n"
        "- Each readme section should represent a major functional component or feature\n"
        "- Consider dependencies between sections\n\n"
        "IMPORTANT: Make sure each section is distinct and doesn't overlap with other sections.\n"
    ),
    "docs_dependency_tasks": (
        "Review the following target documentation section and determine if it depends on any other sections.\n"
        "Target section: {target_task}\n"
        "Other sections:\n{subtasks}\n\n"
        "Dependencies should always be one way, marking which sections a section depends on.\n"
        "If any dependencies are found, link the uuid of the target section "
        "with a list of uuids for any sections it depends on.\n"
        "IMPORTANT: do not create circular dependencies.\n"
    ),
    "docs_generate_system_prompts": (
        "Your task is to create a comprehensive system prompt that will guide an AI agent in creating "
        "documentation for the entire feature and all its sections:\n\n"
        "Documentation sections: {issues}\n"
        "Sections: {tasks}\n\n"
        "Create a single system prompt that:\n"
        "1. Defines the AI's role and expertise needed for creating comprehensive documentation\n"
        "2. Provides comprehensive context about the feature and its documentation needs\n"
        "3. Sets clear guidelines for documentation style and tone\n"
        "4. Specifies documentation standards and best practices to follow\n"
        "5. Includes requirements for examples, code snippets, and visual aids\n"
        "6. Explains how different documentation sections relate to each other\n"
        "7. Provides guidance on maintaining consistency across all documentation\n\n"
        "Format the system prompt as follows:\n"
        "---\n"
        "Documentation Overview:\n"
        "[High-level description of the documentation goals andSubsections target audience]\n\n"
        "AI Role and Expertise:\n"
        "[Define the AI's role as a technical writer and required expertise]\n\n"
        "Documentation Context:\n"
        "[Comprehensive context about the feature and its documentation needs]\n\n"
        "Documentation Guidelines:\n"
        "- [List documentation requirements and style guidelines]\n\n"
        "Writing Standards:\n"
        "- [List writing standards and best practices]\n\n"
        "Section Dependencies and Relationships:\n"
        "[Explain how documentation sections relate to each other]\n\n"
        "Quality and Review Requirements:\n"
        "[Specify quality standards and review requirements]\n"
        "---\n"
    ),
    
}
